name: "avantsoft"

services:
  rails:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
    - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Rails default composer file says to use only "forwardPorts" on
    # **devcontainer.json**. However, we also need to add the ports here so we
    # can access it using Devcontainer CLI
    ports:
      - "3000:3000"
